# Generated by Django 2.1.2 on 2018-12-26 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_auto_20181212_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawChem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_cas', models.CharField(blank=True, max_length=100, null=True, verbose_name='Raw CAS')),
                ('raw_chem_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Raw chemical name')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
