# Generated by Django 2.1.2 on 2018-12-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0079_rename_raw_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsstoxsubstance',
            name='extracted_chemical',
        ),
        migrations.AlterField(
            model_name='dsstoxsubstance',
            name='rawchem_ptr_temp',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.RawChem'),
        ),
    ]
