# Generated by Django 2.1.2 on 2018-12-28 18:36

import dashboard.models.extracted_chemical
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_rename_rawchem_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedchemical',
            name='central_wf_analysis',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.extracted_chemical.validate_wf_analysis]),
        ),
        migrations.AddField(
            model_name='extractedchemical',
            name='lower_wf_analysis',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.extracted_chemical.validate_wf_analysis]),
        ),
        migrations.AddField(
            model_name='extractedchemical',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Script'),
        ),
        migrations.AddField(
            model_name='extractedchemical',
            name='upper_wf_analysis',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=16, null=True, validators=[dashboard.models.extracted_chemical.validate_wf_analysis]),
        ),
    ]
